SCREEN_HEIGHT = 720
SCREEN_WIDTH = 1280

ASSETS_CHARACTERS = "assets/images/peep/"
ASSETS_BG_FOLDER = "assets/images/background/"
ASSETS_IMAGES_FOLDER = "assets/images/"
ASSETS_FONT_FOLDER = "assets/font/"
ASSETS_SOUNDS = "assets/sounds/"

FPS = 60

WHITE = (255, 255, 255)
BLACK = (35, 40, 41)

GRAVITY = 1
GROUND = SCREEN_HEIGHT - 40
SCROLL_INCREMENT = 3
